"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nightscout_osx_menubar.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'requests',
        'rumps',
        'simplejson',
    ],
    'plist': {
        'CFBundleName': 'Nightscout Menubar',
        'CFBundleDisplayName': 'Nightscout Menubar',
        'CFBundleGetInfoString': 'Nightscout Menubar',
        'CFBundleIdentifier': 'com.warkmilson.nightscout.menubar',
        'LSPrefersPPC': True,
        'LSUIElement': True,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
